### ISSUE TITLE
Версия драйвера не подходит под текущую версию.

### ISSUE THREAD

**Issue by ram876876** [yandex/YandexDriver#16]
Здравствуйте! Некоторое время я использовал вебдрайвер яндекса с подключенными плагинами без проблем. У меня стоит версия браузера 23.7.0.1867 beta (64-bit), а версия вебрайвера от 17 мая. Сегодня вышла ошибка, что для вебрайвера надо использовать options вместо chrome_options в моем коде, после исправления программа стала закрываться с ошибкой о несоответствии версий. Вебрайвер не запускается даже во вашему туториалу.

```
[10636:11088:0630/135351.800:ERROR:isolated_origin_util.cc(74)] Ignoring port number in isolated origin: chrome://custo
[10636:11088:0630/135351.816:ERROR:chrome_browser_cloud_management_controller.cc(166)] Cloud management controller initialization aborted as CBCM is not enabled.

DevTools listening on ws://127.0.0.1:56279/devtools/browser/db78480e-cb5f-4b4f-9868-99827bb7af9c
[13472:9108:0630/135352.370:ERROR:ssl_client_socket_impl.cc(1280)] handshake failed; returned -1, SSL error code 1, net_error -215
[13472:9108:0630/135352.454:ERROR:ssl_client_socket_impl.cc(1280)] handshake failed; returned -1, SSL error code 1, net_error -215
Traceback (most recent call last):
  File "D:\Pr\FillKPT\0.py", line 6, in <module>
    driver = webdriver.Chrome(binary_yandex_driver_file, options=options)
  File "C:\Users\Я\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Я\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Я\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Я\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Я\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 112
Current browser version is 114.0.5735.1867 with binary path C:\Users\Я\AppData\Local\Yandex\YandexBrowser\Application\browser.exe
```

Вот так ранее подключал вебдрайвер
```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
executable_path = "C:\webDriver\yandexdriver.exe"#Путь к веб драйверу
os.environ["webdriver.chrome.driver"] = executable_path
chrome_options = Options()
chrome_options.add_extension('C:\webDriver\extension_1_2_8_0.crx')#Пути к плагинам
chrome_options.add_extension('C:\webDriver\extension_1_2_13_0.crx')
driver = webdriver.Chrome(executable_path=executable_path, chrome_options=chrome_options)
```
Можете помочь решением данной проблемы?

**Comment by ram876876** [comment]
Здравствуйте! Моя предыдущая проблема решилась, когда вышла новая версия вебдрайвера, но это проблема недавно опять появилась. Версия вебдрайвера не подходит. Скоро ли выпустят новую версию для windows? Спасибо!
